// ═══════════════════════════════════════════════════════
// Curated Recipe Pool — 30-50 structured recipes for P0
//
// Coverage targets:
//   荤菜 12-15, 素菜 10-12, 汤 6-8, 主食 4-6
//   Scenarios: quick_dinner, weekend_date, anniversary, lazy_meal
//   Flavors: acid-spicy, mild, savory, refreshing, rich
//   Difficulty spread: 1 (40%) / 2 (40%) / 3 (20%)
//
// @工程师: expand to 30-50 entries
// ═══════════════════════════════════════════════════════

import type { Recipe, Ingredient, Seasoning, CookingStep } from '../../../shared/types';

// Helper: recipe without id/stats/isCurated/source (filled by seeder)
type SeedRecipe = Omit<Recipe, 'id' | 'source' | 'isCurated' | 'stats' | 'imageUrl'>;

export const seedRecipes: SeedRecipe[] = [
  // ── 荤菜 (meat) ────────────────────────────────────
  {
    name: '酸辣牛肉片',
    type: '荤菜',
    tags: ['家常菜', '快手菜', '下饭菜', '双人餐'],
    scenarioTags: ['quick_dinner', 'weekend_date'],
    flavors: ['酸辣', '下饭', '开胃'],
    primaryFlavor: '酸辣',
    equipmentNeeded: ['stove'],
    totalTimeMinutes: 25,
    difficulty: 2,
    servings: 2,
    ingredients: [
      { name: '牛肉', amount: '300g', category: 'meat', isStaple: false },
      { name: '青椒', amount: '2个', category: 'vegetable', isStaple: false },
      { name: '蒜', amount: '3瓣', category: 'other', isStaple: true },
    ],
    seasonings: [
      { name: '生抽', amount: '2勺', isStaple: true },
      { name: '醋', amount: '1勺', isStaple: true },
      { name: '淀粉', amount: '1勺', isStaple: true },
    ],
    steps: [
      { order: 1, description: '牛肉切薄片，加生抽、淀粉腌制10分钟', durationMinutes: 10, assignedTo: 'B' },
      { order: 2, description: '青椒切丝，蒜切片', durationMinutes: 3, fireHint: 'off', assignedTo: 'B' },
      { order: 3, description: '热锅凉油，大火炒牛肉至变色盛出', durationMinutes: 3, fireHint: 'high', warning: '不要炒老', assignedTo: 'A' },
      { order: 4, description: '爆香蒜片，下青椒翻炒', durationMinutes: 2, fireHint: 'high', assignedTo: 'A' },
      { order: 5, description: '牛肉回锅，加醋翻炒均匀出锅', durationMinutes: 2, fireHint: 'high', assignedTo: 'A' },
    ],
  },

  {
    name: '可乐鸡翅',
    type: '荤菜',
    tags: ['家常菜', '快手菜', '双人餐'],
    scenarioTags: ['quick_dinner', 'lazy_meal'],
    flavors: ['咸鲜', '下饭', '甜口'],
    primaryFlavor: '咸鲜',
    equipmentNeeded: ['stove'],
    totalTimeMinutes: 30,
    difficulty: 1,
    servings: 2,
    ingredients: [
      { name: '鸡翅中', amount: '8个', category: 'meat', isStaple: false },
      { name: '可乐', amount: '1罐', category: 'other', isStaple: false },
      { name: '姜', amount: '3片', category: 'other', isStaple: true },
    ],
    seasonings: [
      { name: '生抽', amount: '2勺', isStaple: true },
      { name: '老抽', amount: '1勺', isStaple: true },
    ],
    steps: [
      { order: 1, description: '鸡翅洗净，两面划刀', durationMinutes: 3, fireHint: 'off', assignedTo: 'B' },
      { order: 2, description: '冷水下锅焯水，捞出沥干', durationMinutes: 5, fireHint: 'high', assignedTo: 'A' },
      { order: 3, description: '热锅少油，煎鸡翅至两面金黄', durationMinutes: 8, fireHint: 'medium', assignedTo: 'A' },
      { order: 4, description: '倒入可乐、生抽、老抽、姜片，中小火炖15分钟', durationMinutes: 15, fireHint: 'medium', assignedTo: 'A' },
      { order: 5, description: '大火收汁，翻匀出锅', durationMinutes: 2, fireHint: 'high', assignedTo: 'A' },
    ],
  },

  {
    name: '青椒鸡丁',
    type: '荤菜',
    tags: ['家常菜', '快手菜', '下饭菜'],
    scenarioTags: ['quick_dinner'],
    flavors: ['咸鲜', '下饭', '微辣'],
    primaryFlavor: '咸鲜',
    equipmentNeeded: ['stove'],
    totalTimeMinutes: 20,
    difficulty: 1,
    servings: 2,
    ingredients: [
      { name: '鸡胸肉', amount: '250g', category: 'meat', isStaple: false },
      { name: '青椒', amount: '2个', category: 'vegetable', isStaple: false },
      { name: '蒜', amount: '3瓣', category: 'other', isStaple: true },
      { name: '姜', amount: '2片', category: 'other', isStaple: true },
    ],
    seasonings: [
      { name: '生抽', amount: '1勺', isStaple: true },
      { name: '料酒', amount: '1勺', isStaple: true },
      { name: '淀粉', amount: '1勺', isStaple: true },
    ],
    steps: [
      { order: 1, description: '鸡胸肉切丁，加料酒生抽淀粉腌制', durationMinutes: 8, assignedTo: 'B' },
      { order: 2, description: '青椒切块，姜蒜切片', durationMinutes: 3, fireHint: 'off', assignedTo: 'B' },
      { order: 3, description: '热油下鸡丁滑炒至变色盛出', durationMinutes: 3, fireHint: 'high', assignedTo: 'A' },
      { order: 4, description: '爆香姜蒜，下青椒翻炒', durationMinutes: 2, fireHint: 'high', assignedTo: 'A' },
      { order: 5, description: '鸡丁回锅，加生抽翻炒均匀', durationMinutes: 2, fireHint: 'high', assignedTo: 'A' },
    ],
  },

  // ── 更多荤菜 (+9) ──
  {
    name: '宫保鸡丁', type: '荤菜', tags: ['家常菜', '快手菜', '下饭菜'], scenarioTags: ['quick_dinner'],
    flavors: ['辣', '下饭', '开胃'], primaryFlavor: '辣', equipmentNeeded: ['stove'],
    totalTimeMinutes: 25, difficulty: 2, servings: 2,
    ingredients: [
      { name: '鸡胸肉', amount: '250g', category: 'meat', isStaple: false },
      { name: '花生米', amount: '50g', category: 'other', isStaple: false },
      { name: '干辣椒', amount: '5个', category: 'other', isStaple: true },
      { name: '葱姜蒜', amount: '适量', category: 'other', isStaple: true },
    ],
    seasonings: [{ name: '生抽', amount: '1勺', isStaple: true }, { name: '醋', amount: '1勺', isStaple: true }, { name: '糖', amount: '1勺', isStaple: true }, { name: '淀粉', amount: '1勺', isStaple: true }],
    steps: [
      { order: 1, description: '鸡胸肉切丁加生抽淀粉腌制', durationMinutes: 10, assignedTo: 'B' },
      { order: 2, description: '葱姜蒜切末干辣椒切段，调碗汁(生抽+醋+糖+淀粉+水)', durationMinutes: 3, fireHint: 'off', assignedTo: 'together' },
      { order: 3, description: '热油滑炒鸡丁至变色盛出', durationMinutes: 3, fireHint: 'high', assignedTo: 'A' },
      { order: 4, description: '爆香干辣椒葱姜蒜，鸡丁回锅倒碗汁加花生米大火收汁', durationMinutes: 3, fireHint: 'high', assignedTo: 'A' },
    ],
  },
  {
    name: '红烧排骨', type: '荤菜', tags: ['家常菜', '硬菜', '双人餐'], scenarioTags: ['weekend_date', 'anniversary'],
    flavors: ['咸鲜', '下饭', '甜口'], primaryFlavor: '咸鲜', equipmentNeeded: ['stove'],
    totalTimeMinutes: 50, difficulty: 2, servings: 2,
    ingredients: [
      { name: '排骨', amount: '500g', category: 'meat', isStaple: false },
      { name: '葱姜', amount: '适量', category: 'other', isStaple: true },
    ],
    seasonings: [{ name: '生抽', amount: '2勺', isStaple: true }, { name: '老抽', amount: '1勺', isStaple: true }, { name: '料酒', amount: '1勺', isStaple: true }, { name: '冰糖', amount: '10g', isStaple: false }, { name: '八角', amount: '1个', isStaple: false }],
    steps: [
      { order: 1, description: '排骨冷水下锅焯水撇浮沫捞出', durationMinutes: 8, fireHint: 'high', assignedTo: 'B' },
      { order: 2, description: '热锅少油下冰糖小火炒糖色至焦糖色', durationMinutes: 3, fireHint: 'low', warning: '别炒糊会发苦', assignedTo: 'A' },
      { order: 3, description: '下排骨翻炒上色，加葱姜八角生抽老抽料酒，倒开水没过小火炖30分钟', durationMinutes: 30, fireHint: 'low', assignedTo: 'A' },
      { order: 4, description: '大火收汁至浓稠出锅', durationMinutes: 5, fireHint: 'high', assignedTo: 'A' },
    ],
  },
  {
    name: '鱼香肉丝', type: '荤菜', tags: ['家常菜', '下饭菜', '快手菜'], scenarioTags: ['quick_dinner'],
    flavors: ['酸辣', '下饭', '开胃'], primaryFlavor: '酸辣', equipmentNeeded: ['stove'],
    totalTimeMinutes: 20, difficulty: 2, servings: 2,
    ingredients: [
      { name: '猪里脊', amount: '200g', category: 'meat', isStaple: false },
      { name: '木耳', amount: '50g', category: 'vegetable', isStaple: false },
      { name: '胡萝卜', amount: '半根', category: 'vegetable', isStaple: false },
      { name: '青椒', amount: '1个', category: 'vegetable', isStaple: false },
      { name: '葱姜蒜', amount: '适量', category: 'other', isStaple: true },
    ],
    seasonings: [{ name: '生抽', amount: '1勺', isStaple: true }, { name: '醋', amount: '1勺', isStaple: true }, { name: '糖', amount: '1勺', isStaple: true }, { name: '豆瓣酱', amount: '1勺', isStaple: false }, { name: '淀粉', amount: '1勺', isStaple: true }],
    steps: [
      { order: 1, description: '里脊切丝加淀粉生抽腌制，木耳胡萝卜青椒切丝', durationMinutes: 10, assignedTo: 'B' },
      { order: 2, description: '调鱼香汁：生抽+醋+糖+淀粉+水搅匀', durationMinutes: 1, assignedTo: 'together' },
      { order: 3, description: '热油滑炒肉丝至变色盛出', durationMinutes: 2, fireHint: 'high', assignedTo: 'A' },
      { order: 4, description: '爆香葱姜蒜+豆瓣酱，下蔬菜丝翻炒，肉丝回锅倒汁翻匀', durationMinutes: 5, fireHint: 'high', assignedTo: 'A' },
    ],
  },
  {
    name: '回锅肉', type: '荤菜', tags: ['家常菜', '下饭菜', '硬菜'], scenarioTags: ['quick_dinner', 'weekend_date'],
    flavors: ['辣', '下饭', '开胃'], primaryFlavor: '辣', equipmentNeeded: ['stove'],
    totalTimeMinutes: 30, difficulty: 2, servings: 2,
    ingredients: [
      { name: '五花肉', amount: '300g', category: 'meat', isStaple: false },
      { name: '青蒜', amount: '3根', category: 'vegetable', isStaple: false },
      { name: '姜', amount: '3片', category: 'other', isStaple: true },
    ],
    seasonings: [{ name: '豆瓣酱', amount: '1勺', isStaple: false }, { name: '生抽', amount: '1勺', isStaple: true }, { name: '豆豉', amount: '少许', isStaple: false }],
    steps: [
      { order: 1, description: '五花肉整块冷水煮20分钟至筷子能扎透，捞出放凉切薄片', durationMinutes: 20, fireHint: 'medium', assignedTo: 'B' },
      { order: 2, description: '青蒜切斜段', durationMinutes: 2, fireHint: 'off', assignedTo: 'together' },
      { order: 3, description: '热锅少油下肉片中火煸出油至微卷，下豆瓣酱豆豉姜片炒出红油', durationMinutes: 6, fireHint: 'medium', assignedTo: 'A' },
      { order: 4, description: '下青蒜大火翻炒至断生加生抽翻匀', durationMinutes: 1, fireHint: 'high', assignedTo: 'A' },
    ],
  },
  {
    name: '蒜蓉虾', type: '荤菜', tags: ['快手菜', '双人餐'], scenarioTags: ['weekend_date', 'anniversary'],
    flavors: ['咸鲜', '清淡', '开胃'], primaryFlavor: '咸鲜', equipmentNeeded: ['stove'],
    totalTimeMinutes: 15, difficulty: 1, servings: 2,
    ingredients: [
      { name: '大虾', amount: '300g', category: 'meat', isStaple: false },
      { name: '蒜', amount: '6瓣', category: 'other', isStaple: true }, { name: '葱', amount: '1根', category: 'other', isStaple: true },
    ],
    seasonings: [{ name: '生抽', amount: '1勺', isStaple: true }, { name: '料酒', amount: '1勺', isStaple: true }],
    steps: [
      { order: 1, description: '虾开背去虾线加料酒腌制', durationMinutes: 5, assignedTo: 'B' },
      { order: 2, description: '蒜切末葱切花', durationMinutes: 2, fireHint: 'off', assignedTo: 'B' },
      { order: 3, description: '热油小火煸蒜末至金黄出香', durationMinutes: 2, fireHint: 'low', warning: '别炸糊', assignedTo: 'A' },
      { order: 4, description: '下虾大火翻炒至变红加生抽撒葱花', durationMinutes: 3, fireHint: 'high', assignedTo: 'A' },
    ],
  },
  {
    name: '土豆炖牛肉', type: '荤菜', tags: ['家常菜', '硬菜', '双人餐'], scenarioTags: ['weekend_date', 'anniversary'],
    flavors: ['咸鲜', '下饭', '热乎'], primaryFlavor: '咸鲜', equipmentNeeded: ['stove'],
    totalTimeMinutes: 60, difficulty: 2, servings: 2,
    ingredients: [
      { name: '牛腩', amount: '400g', category: 'meat', isStaple: false },
      { name: '土豆', amount: '2个', category: 'vegetable', isStaple: false },
      { name: '胡萝卜', amount: '1根', category: 'vegetable', isStaple: false },
      { name: '葱姜', amount: '适量', category: 'other', isStaple: true },
    ],
    seasonings: [{ name: '生抽', amount: '2勺', isStaple: true }, { name: '老抽', amount: '1勺', isStaple: true }, { name: '料酒', amount: '1勺', isStaple: true }, { name: '八角', amount: '1个', isStaple: false }],
    steps: [
      { order: 1, description: '牛肉切块冷水焯水，土豆胡萝卜切滚刀块', durationMinutes: 10, assignedTo: 'B' },
      { order: 2, description: '热油下葱姜八角爆香下牛肉翻炒，加生抽老抽料酒倒开水小火炖40分钟', durationMinutes: 40, fireHint: 'low', assignedTo: 'A' },
      { order: 3, description: '下土豆胡萝卜继续炖15分钟至软烂', durationMinutes: 15, fireHint: 'medium', assignedTo: 'A' },
      { order: 4, description: '大火收汁翻匀出锅', durationMinutes: 2, fireHint: 'high', assignedTo: 'A' },
    ],
  },
  {
    name: '糖醋里脊', type: '荤菜', tags: ['家常菜', '双人餐'], scenarioTags: ['weekend_date'],
    flavors: ['酸甜', '开胃'], primaryFlavor: '酸甜', equipmentNeeded: ['stove'],
    totalTimeMinutes: 30, difficulty: 2, servings: 2,
    ingredients: [
      { name: '猪里脊', amount: '250g', category: 'meat', isStaple: false },
      { name: '鸡蛋', amount: '1个', category: 'egg_dairy', isStaple: true },
    ],
    seasonings: [{ name: '番茄酱', amount: '3勺', isStaple: false }, { name: '醋', amount: '1勺', isStaple: true }, { name: '糖', amount: '2勺', isStaple: true }, { name: '淀粉', amount: '适量', isStaple: true }],
    steps: [
      { order: 1, description: '里脊切条加蛋液淀粉抓匀挂糊', durationMinutes: 8, assignedTo: 'B' },
      { order: 2, description: '调糖醋汁：番茄酱+醋+糖+水+淀粉搅匀', durationMinutes: 1, assignedTo: 'together' },
      { order: 3, description: '热油六成热逐条下里脊炸金黄捞出，油温升高复炸30秒至酥脆', durationMinutes: 10, fireHint: 'medium', assignedTo: 'A' },
      { order: 4, description: '留底油倒糖醋汁煮至浓稠下里脊裹汁出锅', durationMinutes: 2, fireHint: 'medium', assignedTo: 'A' },
    ],
  },
  {
    name: '蚝油牛肉', type: '荤菜', tags: ['快手菜', '家常菜', '下饭菜'], scenarioTags: ['quick_dinner'],
    flavors: ['咸鲜', '下饭'], primaryFlavor: '咸鲜', equipmentNeeded: ['stove'],
    totalTimeMinutes: 15, difficulty: 1, servings: 2,
    ingredients: [
      { name: '牛肉', amount: '250g', category: 'meat', isStaple: false },
      { name: '洋葱', amount: '半个', category: 'vegetable', isStaple: false },
      { name: '青椒', amount: '1个', category: 'vegetable', isStaple: false },
    ],
    seasonings: [{ name: '蚝油', amount: '2勺', isStaple: false }, { name: '生抽', amount: '1勺', isStaple: true }, { name: '淀粉', amount: '1勺', isStaple: true }],
    steps: [
      { order: 1, description: '牛肉切薄片加生抽淀粉腌制，洋葱青椒切块', durationMinutes: 8, assignedTo: 'B' },
      { order: 2, description: '热油大火滑炒牛肉至变色盛出', durationMinutes: 2, fireHint: 'high', assignedTo: 'A' },
      { order: 3, description: '炒香洋葱青椒，牛肉回锅加蚝油翻炒均匀', durationMinutes: 3, fireHint: 'high', assignedTo: 'A' },
    ],
  },
  {
    name: '葱爆羊肉', type: '荤菜', tags: ['快手菜', '家常菜', '下饭菜'], scenarioTags: ['quick_dinner'],
    flavors: ['咸鲜', '下饭', '微辣'], primaryFlavor: '咸鲜', equipmentNeeded: ['stove'],
    totalTimeMinutes: 15, difficulty: 1, servings: 2,
    ingredients: [
      { name: '羊肉片', amount: '300g', category: 'meat', isStaple: false },
      { name: '大葱', amount: '2根', category: 'vegetable', isStaple: false },
      { name: '姜', amount: '3片', category: 'other', isStaple: true },
    ],
    seasonings: [{ name: '生抽', amount: '1勺', isStaple: true }, { name: '料酒', amount: '1勺', isStaple: true }, { name: '孜然粉', amount: '半勺', isStaple: false }],
    steps: [
      { order: 1, description: '大葱切斜段姜切丝', durationMinutes: 2, fireHint: 'off', assignedTo: 'B' },
      { order: 2, description: '热锅大火直接下羊肉片煸炒出油加料酒去膻', durationMinutes: 3, fireHint: 'high', assignedTo: 'A' },
      { order: 3, description: '下姜丝葱段大火爆炒，加生抽孜然粉翻匀出锅', durationMinutes: 2, fireHint: 'high', assignedTo: 'A' },
    ],
  },

  // ── 素菜 (veg) ──────────────────────────────────────
  {
    name: '蒜蓉生菜',
    type: '素菜',
    tags: ['快手菜', '凉拌菜', '开胃菜'],
    scenarioTags: ['quick_dinner', 'lazy_meal'],
    flavors: ['清淡', '开胃', '解腻'],
    primaryFlavor: '清淡',
    equipmentNeeded: ['stove'],
    totalTimeMinutes: 8,
    difficulty: 1,
    servings: 2,
    ingredients: [
      { name: '生菜', amount: '2棵', category: 'vegetable', isStaple: false },
      { name: '蒜', amount: '4瓣', category: 'other', isStaple: true },
    ],
    seasonings: [
      { name: '生抽', amount: '1勺', isStaple: true },
      { name: '蚝油', amount: '1勺', isStaple: false },
    ],
    steps: [
      { order: 1, description: '生菜洗净撕成小段，蒜切末', durationMinutes: 3, fireHint: 'off', assignedTo: 'B' },
      { order: 2, description: '水开焯生菜30秒捞出装盘', durationMinutes: 2, fireHint: 'high', warning: '不要焯太久会软烂', assignedTo: 'A' },
      { order: 3, description: '热油爆香蒜末，淋生抽蚝油煮开，浇在生菜上', durationMinutes: 3, fireHint: 'medium', assignedTo: 'A' },
    ],
  },

  {
    name: '清炒油麦菜',
    type: '素菜',
    tags: ['快手菜', '家常菜', '减脂餐'],
    scenarioTags: ['quick_dinner', 'lazy_meal'],
    flavors: ['清淡', '解腻', '清爽'],
    primaryFlavor: '清淡',
    equipmentNeeded: ['stove'],
    totalTimeMinutes: 8,
    difficulty: 1,
    servings: 2,
    ingredients: [
      { name: '油麦菜', amount: '300g', category: 'vegetable', isStaple: false },
      { name: '蒜', amount: '3瓣', category: 'other', isStaple: true },
    ],
    seasonings: [
      { name: '盐', amount: '适量', isStaple: true },
    ],
    steps: [
      { order: 1, description: '油麦菜洗净切段，蒜切片', durationMinutes: 3, fireHint: 'off', assignedTo: 'B' },
      { order: 2, description: '热油爆香蒜片', durationMinutes: 1, fireHint: 'high', assignedTo: 'A' },
      { order: 3, description: '下油麦菜大火快炒，加盐翻匀出锅', durationMinutes: 2, fireHint: 'high', warning: '全程大火，不超过3分钟', assignedTo: 'A' },
    ],
  },

  {
    name: '凉拌黄瓜',
    type: '素菜',
    tags: ['凉拌菜', '快手菜', '开胃菜', '懒人菜'],
    scenarioTags: ['quick_dinner', 'lazy_meal'],
    flavors: ['开胃', '解腻', '清爽'],
    primaryFlavor: '清爽',
    equipmentNeeded: ['none'],
    totalTimeMinutes: 6,
    difficulty: 1,
    servings: 2,
    ingredients: [
      { name: '黄瓜', amount: '2根', category: 'vegetable', isStaple: false },
      { name: '蒜', amount: '3瓣', category: 'other', isStaple: true },
    ],
    seasonings: [
      { name: '醋', amount: '2勺', isStaple: true },
      { name: '生抽', amount: '1勺', isStaple: true },
      { name: '香油', amount: '少许', isStaple: false },
    ],
    steps: [
      { order: 1, description: '黄瓜拍碎切段', durationMinutes: 2, fireHint: 'off', assignedTo: 'together' },
      { order: 2, description: '蒜切末，加醋、生抽、香油调汁', durationMinutes: 2, fireHint: 'off', assignedTo: 'B' },
      { order: 3, description: '料汁浇在黄瓜上拌匀', durationMinutes: 1, fireHint: 'off', assignedTo: 'together' },
    ],
  },

  // ── 更多素菜 (+7) ──
  {
    name: '酸辣土豆丝', type: '素菜', tags: ['家常菜', '快手菜', '下饭菜', '开胃菜'], scenarioTags: ['quick_dinner'],
    flavors: ['酸辣', '下饭', '开胃'], primaryFlavor: '酸辣', equipmentNeeded: ['stove'],
    totalTimeMinutes: 15, difficulty: 1, servings: 2,
    ingredients: [
      { name: '土豆', amount: '2个', category: 'vegetable', isStaple: false },
      { name: '干辣椒', amount: '3个', category: 'other', isStaple: true },
      { name: '蒜', amount: '3瓣', category: 'other', isStaple: true },
    ],
    seasonings: [{ name: '醋', amount: '2勺', isStaple: true }, { name: '盐', amount: '适量', isStaple: true }],
    steps: [
      { order: 1, description: '土豆去皮切细丝，冷水泡去淀粉沥干', durationMinutes: 5, fireHint: 'off', assignedTo: 'B' },
      { order: 2, description: '蒜切片，干辣椒切段', durationMinutes: 1, fireHint: 'off', assignedTo: 'B' },
      { order: 3, description: '热油爆香干辣椒蒜片', durationMinutes: 1, fireHint: 'high', assignedTo: 'A' },
      { order: 4, description: '下土豆丝大火快炒，锅边淋醋加盐，翻匀出锅', durationMinutes: 3, fireHint: 'high', warning: '全程大火保持脆爽', assignedTo: 'A' },
    ],
  },
  {
    name: '麻婆豆腐', type: '素菜', tags: ['家常菜', '下饭菜', '快手菜'], scenarioTags: ['quick_dinner'],
    flavors: ['麻辣', '下饭', '热乎'], primaryFlavor: '麻辣', equipmentNeeded: ['stove'],
    totalTimeMinutes: 15, difficulty: 1, servings: 2,
    ingredients: [
      { name: '嫩豆腐', amount: '1盒', category: 'vegetable', isStaple: false },
      { name: '肉末', amount: '50g', category: 'meat', isStaple: false },
      { name: '葱姜蒜', amount: '适量', category: 'other', isStaple: true },
    ],
    seasonings: [{ name: '豆瓣酱', amount: '1勺', isStaple: false }, { name: '花椒粉', amount: '半勺', isStaple: false }, { name: '生抽', amount: '1勺', isStaple: true }, { name: '淀粉', amount: '1勺', isStaple: true }],
    steps: [
      { order: 1, description: '豆腐切2cm方块，沸水焯1分钟捞出', durationMinutes: 3, fireHint: 'high', assignedTo: 'B' },
      { order: 2, description: '葱姜蒜切末', durationMinutes: 2, fireHint: 'off', assignedTo: 'B' },
      { order: 3, description: '热油炒肉末至变色，下豆瓣酱炒出红油，加姜蒜末', durationMinutes: 3, fireHint: 'medium', assignedTo: 'A' },
      { order: 4, description: '加水烧开下豆腐，小火煮3分钟入味', durationMinutes: 3, fireHint: 'low', assignedTo: 'A' },
      { order: 5, description: '水淀粉勾芡，撒花椒粉葱花出锅', durationMinutes: 1, fireHint: 'medium', assignedTo: 'A' },
    ],
  },
  {
    name: '干煸四季豆', type: '素菜', tags: ['家常菜', '下饭菜'], scenarioTags: ['quick_dinner', 'weekend_date'],
    flavors: ['辣', '下饭', '咸鲜'], primaryFlavor: '辣', equipmentNeeded: ['stove'],
    totalTimeMinutes: 20, difficulty: 2, servings: 2,
    ingredients: [
      { name: '四季豆', amount: '300g', category: 'vegetable', isStaple: false },
      { name: '干辣椒', amount: '5个', category: 'other', isStaple: true },
      { name: '蒜', amount: '4瓣', category: 'other', isStaple: true },
    ],
    seasonings: [{ name: '生抽', amount: '1勺', isStaple: true }, { name: '盐', amount: '适量', isStaple: true }],
    steps: [
      { order: 1, description: '四季豆去筋掰段洗净沥干', durationMinutes: 5, fireHint: 'off', assignedTo: 'B' },
      { order: 2, description: '干辣椒切段蒜切片', durationMinutes: 2, fireHint: 'off', assignedTo: 'B' },
      { order: 3, description: '热锅不放油，下四季豆中火干煸至虎皮色盛出', durationMinutes: 8, fireHint: 'medium', warning: '耐心煸透，生四季豆有毒', assignedTo: 'A' },
      { order: 4, description: '热油爆香干辣椒蒜片，四季豆回锅加生抽盐翻匀', durationMinutes: 2, fireHint: 'high', assignedTo: 'A' },
    ],
  },
  {
    name: '地三鲜', type: '素菜', tags: ['家常菜', '下饭菜'], scenarioTags: ['quick_dinner', 'weekend_date'],
    flavors: ['咸鲜', '下饭'], primaryFlavor: '咸鲜', equipmentNeeded: ['stove'],
    totalTimeMinutes: 25, difficulty: 2, servings: 2,
    ingredients: [
      { name: '土豆', amount: '1个', category: 'vegetable', isStaple: false },
      { name: '茄子', amount: '1根', category: 'vegetable', isStaple: false },
      { name: '青椒', amount: '1个', category: 'vegetable', isStaple: false },
      { name: '蒜', amount: '4瓣', category: 'other', isStaple: true },
    ],
    seasonings: [{ name: '生抽', amount: '2勺', isStaple: true }, { name: '老抽', amount: '半勺', isStaple: true }, { name: '糖', amount: '半勺', isStaple: true }, { name: '淀粉', amount: '1勺', isStaple: true }],
    steps: [
      { order: 1, description: '土豆茄子青椒切滚刀块，茄子撒盐腌10分钟挤水', durationMinutes: 10, assignedTo: 'B' },
      { order: 2, description: '调碗汁：生抽+老抽+糖+淀粉+水搅匀', durationMinutes: 1, assignedTo: 'together' },
      { order: 3, description: '热油分别炸土豆至金黄、茄子至软，青椒过油', durationMinutes: 8, fireHint: 'medium', assignedTo: 'A' },
      { order: 4, description: '留底油爆香蒜末，所有食材回锅倒碗汁大火收汁', durationMinutes: 2, fireHint: 'high', assignedTo: 'A' },
    ],
  },
  {
    name: '手撕包菜', type: '素菜', tags: ['家常菜', '快手菜', '下饭菜'], scenarioTags: ['quick_dinner'],
    flavors: ['辣', '下饭', '开胃'], primaryFlavor: '辣', equipmentNeeded: ['stove'],
    totalTimeMinutes: 10, difficulty: 1, servings: 2,
    ingredients: [
      { name: '包菜', amount: '半个', category: 'vegetable', isStaple: false },
      { name: '干辣椒', amount: '4个', category: 'other', isStaple: true },
      { name: '蒜', amount: '4瓣', category: 'other', isStaple: true },
    ],
    seasonings: [{ name: '生抽', amount: '1勺', isStaple: true }, { name: '醋', amount: '1勺', isStaple: true }, { name: '蚝油', amount: '1勺', isStaple: false }],
    steps: [
      { order: 1, description: '包菜手撕成片洗净沥干，蒜切片干辣椒切段', durationMinutes: 3, fireHint: 'off', assignedTo: 'B' },
      { order: 2, description: '热油爆香干辣椒蒜片', durationMinutes: 1, fireHint: 'high', assignedTo: 'A' },
      { order: 3, description: '下包菜大火爆炒至变软，锅边淋生抽醋蚝油翻匀', durationMinutes: 3, fireHint: 'high', assignedTo: 'A' },
    ],
  },
  {
    name: '番茄炒蛋', type: '素菜', tags: ['家常菜', '快手菜', '下饭菜', '懒人菜'], scenarioTags: ['quick_dinner', 'lazy_meal'],
    flavors: ['酸甜', '下饭'], primaryFlavor: '酸甜', equipmentNeeded: ['stove'],
    totalTimeMinutes: 10, difficulty: 1, servings: 2,
    ingredients: [
      { name: '番茄', amount: '2个', category: 'vegetable', isStaple: false },
      { name: '鸡蛋', amount: '3个', category: 'egg_dairy', isStaple: true },
      { name: '葱', amount: '1根', category: 'other', isStaple: true },
    ],
    seasonings: [{ name: '盐', amount: '适量', isStaple: true }, { name: '糖', amount: '半勺', isStaple: true }],
    steps: [
      { order: 1, description: '番茄切块，鸡蛋打散加盐搅匀，葱切花', durationMinutes: 3, fireHint: 'off', assignedTo: 'B' },
      { order: 2, description: '热油炒蛋至凝固盛出', durationMinutes: 2, fireHint: 'high', assignedTo: 'A' },
      { order: 3, description: '炒番茄至出汁变软，加糖调味', durationMinutes: 3, fireHint: 'medium', assignedTo: 'A' },
      { order: 4, description: '鸡蛋回锅翻炒均匀撒葱花出锅', durationMinutes: 1, fireHint: 'high', assignedTo: 'A' },
    ],
  },
  {
    name: '清炒西兰花', type: '素菜', tags: ['快手菜', '减脂餐', '家常菜'], scenarioTags: ['quick_dinner', 'lazy_meal'],
    flavors: ['清淡', '解腻', '清爽'], primaryFlavor: '清淡', equipmentNeeded: ['stove'],
    totalTimeMinutes: 10, difficulty: 1, servings: 2,
    ingredients: [
      { name: '西兰花', amount: '1颗', category: 'vegetable', isStaple: false },
      { name: '蒜', amount: '3瓣', category: 'other', isStaple: true },
    ],
    seasonings: [{ name: '盐', amount: '适量', isStaple: true }, { name: '蚝油', amount: '1勺', isStaple: false }],
    steps: [
      { order: 1, description: '西兰花掰小朵焯水1分钟捞出', durationMinutes: 4, fireHint: 'high', assignedTo: 'B' },
      { order: 2, description: '蒜切片', durationMinutes: 1, fireHint: 'off', assignedTo: 'B' },
      { order: 3, description: '热油爆香蒜片，下西兰花大火翻炒加盐蚝油', durationMinutes: 2, fireHint: 'high', assignedTo: 'A' },
    ],
  },

  // ── 汤 (soup) ───────────────────────────────────────
  {
    name: '番茄蛋花汤',
    type: '汤',
    tags: ['家常菜', '快手菜'],
    scenarioTags: ['quick_dinner', 'lazy_meal'],
    flavors: ['清淡', '开胃', '想喝汤'],
    primaryFlavor: '清淡',
    equipmentNeeded: ['stove'],
    totalTimeMinutes: 12,
    difficulty: 1,
    servings: 2,
    ingredients: [
      { name: '番茄', amount: '2个', category: 'vegetable', isStaple: false },
      { name: '鸡蛋', amount: '2个', category: 'egg_dairy', isStaple: true },
      { name: '葱', amount: '1根', category: 'other', isStaple: true },
    ],
    seasonings: [
      { name: '盐', amount: '适量', isStaple: true },
      { name: '香油', amount: '少许', isStaple: false },
    ],
    steps: [
      { order: 1, description: '番茄切块，鸡蛋打散，葱切花', durationMinutes: 3, fireHint: 'off', assignedTo: 'B' },
      { order: 2, description: '热油炒番茄至出汁，加水煮开', durationMinutes: 5, fireHint: 'medium', assignedTo: 'A' },
      { order: 3, description: '转圈倒入蛋液，搅拌成蛋花', durationMinutes: 1, fireHint: 'medium', assignedTo: 'A' },
      { order: 4, description: '加盐调味，撒葱花淋香油出锅', durationMinutes: 1, fireHint: 'off', assignedTo: 'A' },
    ],
  },

  {
    name: '紫菜蛋花汤',
    type: '汤',
    tags: ['快手菜', '家常菜', '懒人菜'],
    scenarioTags: ['quick_dinner', 'lazy_meal'],
    flavors: ['清淡', '想喝汤', '清爽'],
    primaryFlavor: '清淡',
    equipmentNeeded: ['stove'],
    totalTimeMinutes: 8,
    difficulty: 1,
    servings: 2,
    ingredients: [
      { name: '紫菜', amount: '1片', category: 'other', isStaple: false },
      { name: '鸡蛋', amount: '2个', category: 'egg_dairy', isStaple: true },
      { name: '葱', amount: '1根', category: 'other', isStaple: true },
    ],
    seasonings: [
      { name: '盐', amount: '适量', isStaple: true },
      { name: '香油', amount: '少许', isStaple: false },
    ],
    steps: [
      { order: 1, description: '紫菜撕碎，鸡蛋打散，葱切花', durationMinutes: 2, fireHint: 'off', assignedTo: 'B' },
      { order: 2, description: '水烧开，下紫菜煮1分钟', durationMinutes: 2, fireHint: 'high', assignedTo: 'A' },
      { order: 3, description: '转圈倒入蛋液成蛋花，加盐、香油、葱花出锅', durationMinutes: 2, fireHint: 'medium', assignedTo: 'A' },
    ],
  },

  // ── 更多汤 (+4) ──
  {
    name: '酸辣汤', type: '汤', tags: ['家常菜', '快手菜', '开胃菜'], scenarioTags: ['quick_dinner', 'late_night'],
    flavors: ['酸辣', '开胃', '热乎', '想喝汤'], primaryFlavor: '酸辣', equipmentNeeded: ['stove'],
    totalTimeMinutes: 15, difficulty: 1, servings: 2,
    ingredients: [
      { name: '豆腐', amount: '半盒', category: 'vegetable', isStaple: false },
      { name: '木耳', amount: '30g', category: 'vegetable', isStaple: false },
      { name: '鸡蛋', amount: '1个', category: 'egg_dairy', isStaple: true },
      { name: '火腿', amount: '50g', category: 'meat', isStaple: false },
    ],
    seasonings: [{ name: '醋', amount: '2勺', isStaple: true }, { name: '白胡椒粉', amount: '1勺', isStaple: false }, { name: '生抽', amount: '1勺', isStaple: true }, { name: '淀粉', amount: '2勺', isStaple: true }, { name: '香油', amount: '少许', isStaple: false }],
    steps: [
      { order: 1, description: '豆腐木耳火腿切丝，鸡蛋打散', durationMinutes: 5, fireHint: 'off', assignedTo: 'B' },
      { order: 2, description: '水烧开下豆腐木耳火腿丝煮3分钟', durationMinutes: 3, fireHint: 'high', assignedTo: 'A' },
      { order: 3, description: '加生抽醋白胡椒调味，水淀粉勾芡', durationMinutes: 2, fireHint: 'medium', assignedTo: 'A' },
      { order: 4, description: '转圈淋入蛋液成蛋花，淋香油出锅', durationMinutes: 1, fireHint: 'medium', assignedTo: 'A' },
    ],
  },
  {
    name: '冬瓜排骨汤', type: '汤', tags: ['家常菜', '硬菜'], scenarioTags: ['weekend_date', 'anniversary'],
    flavors: ['清淡', '解腻', '热乎', '想喝汤'], primaryFlavor: '清淡', equipmentNeeded: ['stove'],
    totalTimeMinutes: 70, difficulty: 2, servings: 2,
    ingredients: [
      { name: '排骨', amount: '300g', category: 'meat', isStaple: false },
      { name: '冬瓜', amount: '300g', category: 'vegetable', isStaple: false },
      { name: '姜', amount: '3片', category: 'other', isStaple: true },
      { name: '葱', amount: '1根', category: 'other', isStaple: true },
    ],
    seasonings: [{ name: '盐', amount: '适量', isStaple: true }, { name: '料酒', amount: '1勺', isStaple: true }],
    steps: [
      { order: 1, description: '排骨冷水焯水撇浮沫捞出，冬瓜去皮切块', durationMinutes: 10, assignedTo: 'B' },
      { order: 2, description: '排骨+姜片+料酒+足量水大火烧开转小火炖40分钟', durationMinutes: 40, fireHint: 'low', assignedTo: 'A' },
      { order: 3, description: '下冬瓜继续炖15分钟至透明', durationMinutes: 15, fireHint: 'medium', assignedTo: 'A' },
      { order: 4, description: '加盐调味撒葱花出锅', durationMinutes: 1, fireHint: 'off', assignedTo: 'together' },
    ],
  },
  {
    name: '菌菇鸡汤', type: '汤', tags: ['家常菜', '硬菜', '双人餐'], scenarioTags: ['weekend_date', 'anniversary'],
    flavors: ['咸鲜', '热乎', '想喝汤'], primaryFlavor: '咸鲜', equipmentNeeded: ['stove'],
    totalTimeMinutes: 55, difficulty: 2, servings: 2,
    ingredients: [
      { name: '鸡腿', amount: '2个', category: 'meat', isStaple: false },
      { name: '香菇', amount: '5朵', category: 'vegetable', isStaple: false },
      { name: '红枣', amount: '5颗', category: 'other', isStaple: false },
      { name: '姜', amount: '3片', category: 'other', isStaple: true },
    ],
    seasonings: [{ name: '盐', amount: '适量', isStaple: true }, { name: '料酒', amount: '1勺', isStaple: true }],
    steps: [
      { order: 1, description: '鸡腿剁块冷水焯水，香菇泡发切片', durationMinutes: 10, assignedTo: 'B' },
      { order: 2, description: '鸡块+姜片+料酒+香菇+红枣+足量水大火烧开', durationMinutes: 5, fireHint: 'high', assignedTo: 'A' },
      { order: 3, description: '转小火炖40分钟至鸡肉软烂', durationMinutes: 40, fireHint: 'low', assignedTo: 'A' },
      { order: 4, description: '加盐调味出锅', durationMinutes: 1, fireHint: 'off', assignedTo: 'together' },
    ],
  },
  {
    name: '豆腐青菜汤', type: '汤', tags: ['快手菜', '减脂餐', '懒人菜'], scenarioTags: ['quick_dinner', 'lazy_meal'],
    flavors: ['清淡', '解腻', '清爽', '想喝汤'], primaryFlavor: '清淡', equipmentNeeded: ['stove'],
    totalTimeMinutes: 8, difficulty: 1, servings: 2,
    ingredients: [
      { name: '嫩豆腐', amount: '半盒', category: 'vegetable', isStaple: false },
      { name: '小青菜', amount: '3棵', category: 'vegetable', isStaple: false },
      { name: '葱', amount: '1根', category: 'other', isStaple: true },
    ],
    seasonings: [{ name: '盐', amount: '适量', isStaple: true }, { name: '香油', amount: '少许', isStaple: false }],
    steps: [
      { order: 1, description: '豆腐切小块，青菜洗净切段，葱切花', durationMinutes: 3, fireHint: 'off', assignedTo: 'B' },
      { order: 2, description: '水烧开下豆腐煮2分钟', durationMinutes: 2, fireHint: 'high', assignedTo: 'A' },
      { order: 3, description: '下青菜煮至变色，加盐香油葱花出锅', durationMinutes: 2, fireHint: 'high', assignedTo: 'A' },
    ],
  },

  // ── 主食 (staple) ──────────────────────────────────
  {
    name: '蛋炒饭',
    type: '主食',
    tags: ['快手菜', '家常菜', '懒人菜', '剩菜改造'],
    scenarioTags: ['quick_dinner', 'lazy_meal'],
    flavors: ['咸鲜', '下饭'],
    primaryFlavor: '咸鲜',
    equipmentNeeded: ['stove', 'rice_cooker'],
    totalTimeMinutes: 15,
    difficulty: 1,
    servings: 2,
    ingredients: [
      { name: '米饭', amount: '2碗（隔夜更好）', category: 'staple', isStaple: true },
      { name: '鸡蛋', amount: '2个', category: 'egg_dairy', isStaple: true },
      { name: '葱', amount: '2根', category: 'other', isStaple: true },
    ],
    seasonings: [
      { name: '盐', amount: '适量', isStaple: true },
    ],
    steps: [
      { order: 1, description: '鸡蛋打散，葱切花', durationMinutes: 2, fireHint: 'off', assignedTo: 'B' },
      { order: 2, description: '热油炒蛋盛出', durationMinutes: 2, fireHint: 'high', assignedTo: 'A' },
      { order: 3, description: '米饭下锅炒散', durationMinutes: 3, fireHint: 'high', assignedTo: 'A' },
      { order: 4, description: '鸡蛋回锅翻炒，加盐、葱花出锅', durationMinutes: 2, fireHint: 'high', assignedTo: 'A' },
    ],
  },

  // ═══════════════════════════════════════════════════════
  // 荤菜 (11 more)
  // ═══════════════════════════════════════════════════════
  {
    name: '辣椒炒肉',
    type: '荤菜',
    tags: ['家常菜', '快手菜', '下饭菜', '双人餐'],
    scenarioTags: ['quick_dinner'],
    flavors: ['辣', '下饭', '开胃'],
    primaryFlavor: '辣',
    equipmentNeeded: ['stove'],
    totalTimeMinutes: 20,
    difficulty: 1,
    servings: 2,
    ingredients: [
      { name: '猪肉（五花/梅花）', amount: '250g', category: 'meat', isStaple: false },
      { name: '青椒', amount: '3个', category: 'vegetable', isStaple: false },
      { name: '蒜', amount: '4瓣', category: 'other', isStaple: true },
      { name: '豆豉', amount: '1勺', category: 'other', isStaple: false },
    ],
    seasonings: [
      { name: '生抽', amount: '1勺', isStaple: true },
      { name: '老抽', amount: '半勺', isStaple: true },
      { name: '盐', amount: '适量', isStaple: true },
    ],
    steps: [
      { order: 1, description: '猪肉切薄片，青椒切块，蒜切片', durationMinutes: 5, fireHint: 'off', assignedTo: 'B' },
      { order: 2, description: '热锅少油，下肉片煸炒出油至微焦', durationMinutes: 5, fireHint: 'high', assignedTo: 'A' },
      { order: 3, description: '下蒜片、豆豉爆香，加生抽老抽翻炒', durationMinutes: 2, fireHint: 'high', assignedTo: 'A' },
      { order: 4, description: '下青椒大火翻炒至断生，加盐出锅', durationMinutes: 3, fireHint: 'high', assignedTo: 'A' },
    ],
  },
  {
    name: '红烧排骨',
    type: '荤菜',
    tags: ['家常菜', '硬菜', '双人餐'],
    scenarioTags: ['weekend_date', 'anniversary'],
    flavors: ['咸鲜', '下饭', '热乎'],
    primaryFlavor: '咸鲜',
    equipmentNeeded: ['stove'],
    totalTimeMinutes: 50,
    difficulty: 2,
    servings: 2,
    ingredients: [
      { name: '排骨', amount: '500g', category: 'meat', isStaple: false },
      { name: '姜', amount: '5片', category: 'other', isStaple: true },
      { name: '葱', amount: '2根', category: 'other', isStaple: true },
      { name: '八角', amount: '2个', category: 'other', isStaple: false },
    ],
    seasonings: [
      { name: '生抽', amount: '2勺', isStaple: true },
      { name: '老抽', amount: '1勺', isStaple: true },
      { name: '料酒', amount: '2勺', isStaple: true },
      { name: '冰糖', amount: '10g', isStaple: false },
    ],
    steps: [
      { order: 1, description: '排骨冷水下锅，加姜片料酒焯水去血沫，捞出沥干', durationMinutes: 8, fireHint: 'high', assignedTo: 'B' },
      { order: 2, description: '热锅少油，下冰糖小火炒糖色至琥珀色', durationMinutes: 3, fireHint: 'low', warning: '火大糖会苦', assignedTo: 'A' },
      { order: 3, description: '下排骨翻炒上色，加姜葱八角生抽老抽', durationMinutes: 3, fireHint: 'high', assignedTo: 'A' },
      { order: 4, description: '加开水没过排骨，大火煮开转中小火炖30分钟', durationMinutes: 30, fireHint: 'medium', assignedTo: 'A' },
      { order: 5, description: '大火收汁至浓稠，翻匀出锅', durationMinutes: 5, fireHint: 'high', assignedTo: 'A' },
    ],
  },
  {
    name: '宫保鸡丁',
    type: '荤菜',
    tags: ['家常菜', '快手菜', '下饭菜'],
    scenarioTags: ['quick_dinner'],
    flavors: ['酸辣', '下饭', '开胃'],
    primaryFlavor: '酸辣',
    equipmentNeeded: ['stove'],
    totalTimeMinutes: 22,
    difficulty: 2,
    servings: 2,
    ingredients: [
      { name: '鸡胸肉', amount: '250g', category: 'meat', isStaple: false },
      { name: '花生米', amount: '50g', category: 'other', isStaple: false },
      { name: '黄瓜', amount: '半根', category: 'vegetable', isStaple: false },
      { name: '干辣椒', amount: '5个', category: 'other', isStaple: true },
      { name: '花椒', amount: '1小勺', category: 'other', isStaple: true },
      { name: '葱', amount: '1根', category: 'other', isStaple: true },
    ],
    seasonings: [
      { name: '生抽', amount: '1勺', isStaple: true },
      { name: '醋', amount: '2勺', isStaple: true },
      { name: '白糖', amount: '1勺', isStaple: true },
      { name: '淀粉', amount: '1勺', isStaple: true },
      { name: '料酒', amount: '1勺', isStaple: true },
    ],
    steps: [
      { order: 1, description: '鸡胸肉切丁，加料酒、生抽、淀粉腌制', durationMinutes: 8, assignedTo: 'B' },
      { order: 2, description: '黄瓜切丁，葱切段。调碗汁：醋+糖+生抽+淀粉+2勺水', durationMinutes: 3, fireHint: 'off', assignedTo: 'B' },
      { order: 3, description: '小火炒花生米至微黄盛出', durationMinutes: 3, fireHint: 'low', assignedTo: 'A' },
      { order: 4, description: '热油爆香花椒干辣椒，下鸡丁滑炒变色', durationMinutes: 3, fireHint: 'high', assignedTo: 'A' },
      { order: 5, description: '下黄瓜丁、葱段翻炒，倒入碗汁，加花生米翻匀出锅', durationMinutes: 2, fireHint: 'high', assignedTo: 'A' },
    ],
  },
  {
    name: '糖醋里脊',
    type: '荤菜',
    tags: ['家常菜', '硬菜', '双人餐'],
    scenarioTags: ['weekend_date'],
    flavors: ['酸甜', '开胃'],
    primaryFlavor: '酸甜',
    equipmentNeeded: ['stove'],
    totalTimeMinutes: 30,
    difficulty: 2,
    servings: 2,
    ingredients: [
      { name: '猪里脊', amount: '300g', category: 'meat', isStaple: false },
      { name: '鸡蛋', amount: '1个', category: 'egg_dairy', isStaple: true },
      { name: '面粉', amount: '50g', category: 'staple', isStaple: true },
    ],
    seasonings: [
      { name: '番茄酱', amount: '3勺', isStaple: false },
      { name: '白糖', amount: '2勺', isStaple: true },
      { name: '白醋', amount: '2勺', isStaple: true },
      { name: '生抽', amount: '1勺', isStaple: true },
      { name: '淀粉', amount: '2勺', isStaple: true },
    ],
    steps: [
      { order: 1, description: '里脊切条，加蛋液、淀粉、少许盐抓匀腌制', durationMinutes: 10, assignedTo: 'B' },
      { order: 2, description: '调糖醋汁：番茄酱+糖+醋+生抽+淀粉+3勺水', durationMinutes: 2, fireHint: 'off', assignedTo: 'B' },
      { order: 3, description: '油温六成热，逐条下里脊炸至金黄捞出', durationMinutes: 8, fireHint: 'medium', warning: '油温别太高，外焦里生', assignedTo: 'A' },
      { order: 4, description: '锅中留底油，倒入糖醋汁煮至浓稠', durationMinutes: 2, fireHint: 'medium', assignedTo: 'A' },
      { order: 5, description: '下里脊快速翻匀，裹满酱汁出锅', durationMinutes: 1, fireHint: 'high', assignedTo: 'A' },
    ],
  },
  {
    name: '蒜蓉虾仁',
    type: '荤菜',
    tags: ['家常菜', '快手菜', '双人餐', '减脂餐'],
    scenarioTags: ['quick_dinner', 'weekend_date'],
    flavors: ['清淡', '咸鲜', '开胃'],
    primaryFlavor: '咸鲜',
    equipmentNeeded: ['stove'],
    totalTimeMinutes: 15,
    difficulty: 1,
    servings: 2,
    ingredients: [
      { name: '虾仁', amount: '250g', category: 'meat', isStaple: false },
      { name: '蒜', amount: '6瓣', category: 'other', isStaple: true },
      { name: '葱', amount: '1根', category: 'other', isStaple: true },
    ],
    seasonings: [
      { name: '料酒', amount: '1勺', isStaple: true },
      { name: '盐', amount: '适量', isStaple: true },
      { name: '白胡椒粉', amount: '少许', isStaple: true },
    ],
    steps: [
      { order: 1, description: '虾仁开背去虾线，加料酒、盐、白胡椒粉腌制5分钟', durationMinutes: 5, fireHint: 'off', assignedTo: 'B' },
      { order: 2, description: '蒜切末，葱切花', durationMinutes: 2, fireHint: 'off', assignedTo: 'B' },
      { order: 3, description: '热油小火炒香蒜末至微黄', durationMinutes: 2, fireHint: 'low', assignedTo: 'A' },
      { order: 4, description: '下虾仁大火翻炒至变色卷曲，撒葱花出锅', durationMinutes: 3, fireHint: 'high', warning: '虾仁变色即可，过火会老', assignedTo: 'A' },
    ],
  },
  {
    name: '红烧肉',
    type: '荤菜',
    tags: ['家常菜', '硬菜', '下饭菜', '双人餐'],
    scenarioTags: ['weekend_date', 'anniversary'],
    flavors: ['咸鲜', '下饭', '热乎'],
    primaryFlavor: '咸鲜',
    equipmentNeeded: ['stove'],
    totalTimeMinutes: 70,
    difficulty: 2,
    servings: 4,
    ingredients: [
      { name: '五花肉', amount: '500g', category: 'meat', isStaple: false },
      { name: '姜', amount: '5片', category: 'other', isStaple: true },
      { name: '葱', amount: '2根', category: 'other', isStaple: true },
      { name: '八角', amount: '2个', category: 'other', isStaple: false },
      { name: '桂皮', amount: '1小块', category: 'other', isStaple: false },
    ],
    seasonings: [
      { name: '生抽', amount: '2勺', isStaple: true },
      { name: '老抽', amount: '1勺', isStaple: true },
      { name: '料酒', amount: '2勺', isStaple: true },
      { name: '冰糖', amount: '15g', isStaple: false },
    ],
    steps: [
      { order: 1, description: '五花肉切3cm方块，冷水下锅加姜片料酒焯水捞出', durationMinutes: 8, fireHint: 'high', assignedTo: 'B' },
      { order: 2, description: '热锅不放油，下肉块煎至表面微黄出油盛出', durationMinutes: 5, fireHint: 'medium', assignedTo: 'A' },
      { order: 3, description: '锅中放少许油，下冰糖小火炒糖色', durationMinutes: 3, fireHint: 'low', warning: '不要炒过会发苦', assignedTo: 'A' },
      { order: 4, description: '下肉块翻炒上色，加姜葱八角桂皮生抽老抽', durationMinutes: 3, fireHint: 'high', assignedTo: 'A' },
      { order: 5, description: '加热水没过肉，大火煮开转小火炖45分钟', durationMinutes: 45, fireHint: 'low', assignedTo: 'A' },
      { order: 6, description: '大火收汁，翻匀至汤汁浓稠出锅', durationMinutes: 5, fireHint: 'high', assignedTo: 'A' },
    ],
  },
  {
    name: '孜然牛肉',
    type: '荤菜',
    tags: ['家常菜', '快手菜', '下饭菜'],
    scenarioTags: ['quick_dinner'],
    flavors: ['辣', '下饭', '开胃'],
    primaryFlavor: '辣',
    equipmentNeeded: ['stove'],
    totalTimeMinutes: 18,
    difficulty: 1,
    servings: 2,
    ingredients: [
      { name: '牛肉', amount: '300g', category: 'meat', isStaple: false },
      { name: '洋葱', amount: '半个', category: 'vegetable', isStaple: false },
      { name: '香菜', amount: '2根', category: 'other', isStaple: false },
    ],
    seasonings: [
      { name: '孜然粉', amount: '2勺', isStaple: false },
      { name: '辣椒面', amount: '1勺', isStaple: false },
      { name: '生抽', amount: '1勺', isStaple: true },
      { name: '料酒', amount: '1勺', isStaple: true },
      { name: '淀粉', amount: '1勺', isStaple: true },
    ],
    steps: [
      { order: 1, description: '牛肉切薄片，加料酒、生抽、淀粉腌制10分钟', durationMinutes: 10, assignedTo: 'B' },
      { order: 2, description: '洋葱切丝', durationMinutes: 2, fireHint: 'off', assignedTo: 'B' },
      { order: 3, description: '热锅凉油，大火滑炒牛肉至变色盛出', durationMinutes: 2, fireHint: 'high', warning: '牛肉不要炒老', assignedTo: 'A' },
      { order: 4, description: '下洋葱丝翻炒出香，牛肉回锅，撒孜然粉辣椒面翻匀', durationMinutes: 2, fireHint: 'high', assignedTo: 'A' },
      { order: 5, description: '撒香菜段翻匀出锅', durationMinutes: 1, fireHint: 'off', assignedTo: 'A' },
    ],
  },
  {
    name: '清蒸鲈鱼',
    type: '荤菜',
    tags: ['家常菜', '硬菜', '双人餐', '减脂餐'],
    scenarioTags: ['weekend_date', 'anniversary'],
    flavors: ['清淡', '咸鲜', '清爽'],
    primaryFlavor: '清淡',
    equipmentNeeded: ['steamer', 'stove'],
    totalTimeMinutes: 25,
    difficulty: 2,
    servings: 2,
    ingredients: [
      { name: '鲈鱼', amount: '1条（约500g）', category: 'meat', isStaple: false },
      { name: '姜', amount: '1块', category: 'other', isStaple: true },
      { name: '葱', amount: '3根', category: 'other', isStaple: true },
    ],
    seasonings: [
      { name: '蒸鱼豉油', amount: '3勺', isStaple: false },
      { name: '料酒', amount: '1勺', isStaple: true },
    ],
    steps: [
      { order: 1, description: '鲈鱼洗净，两面划刀，抹料酒腌制', durationMinutes: 5, fireHint: 'off', assignedTo: 'B' },
      { order: 2, description: '姜一半切片一半切丝，葱白切段，葱绿切丝', durationMinutes: 3, fireHint: 'off', assignedTo: 'B' },
      { order: 3, description: '盘底铺姜片葱段，放上鱼，水开上锅蒸8分钟', durationMinutes: 10, fireHint: 'high', warning: '不要蒸超10分钟，肉会老', assignedTo: 'A' },
      { order: 4, description: '倒掉盘中蒸出的腥水，铺上姜丝葱丝，淋蒸鱼豉油', durationMinutes: 2, fireHint: 'off', assignedTo: 'A' },
      { order: 5, description: '另起锅烧热油，浇在葱姜丝上激香', durationMinutes: 2, fireHint: 'high', assignedTo: 'A' },
    ],
  },
  {
    name: '麻婆豆腐',
    type: '荤菜',
    tags: ['家常菜', '快手菜', '下饭菜', '双人餐'],
    scenarioTags: ['quick_dinner'],
    flavors: ['麻辣', '下饭', '热乎'],
    primaryFlavor: '麻辣',
    equipmentNeeded: ['stove'],
    totalTimeMinutes: 15,
    difficulty: 1,
    servings: 2,
    ingredients: [
      { name: '嫩豆腐', amount: '1盒（400g）', category: 'other', isStaple: false },
      { name: '猪肉末', amount: '100g', category: 'meat', isStaple: false },
      { name: '蒜', amount: '3瓣', category: 'other', isStaple: true },
      { name: '葱', amount: '2根', category: 'other', isStaple: true },
    ],
    seasonings: [
      { name: '豆瓣酱', amount: '1勺', isStaple: false },
      { name: '生抽', amount: '1勺', isStaple: true },
      { name: '花椒粉', amount: '1小勺', isStaple: false },
      { name: '淀粉', amount: '1勺', isStaple: true },
    ],
    steps: [
      { order: 1, description: '豆腐切2cm方块，焯水1分钟捞出（不易碎）', durationMinutes: 3, fireHint: 'high', assignedTo: 'B' },
      { order: 2, description: '蒜切末，葱切花', durationMinutes: 1, fireHint: 'off', assignedTo: 'B' },
      { order: 3, description: '热油炒肉末至变色，下蒜末豆瓣酱炒出红油', durationMinutes: 3, fireHint: 'high', assignedTo: 'A' },
      { order: 4, description: '加半碗水煮开，轻轻滑入豆腐，加生抽中火煮3分钟', durationMinutes: 4, fireHint: 'medium', assignedTo: 'A' },
      { order: 5, description: '水淀粉勾芡，撒花椒粉葱花出锅', durationMinutes: 1, fireHint: 'off', assignedTo: 'A' },
    ],
  },
  {
    name: '葱爆羊肉',
    type: '荤菜',
    tags: ['家常菜', '快手菜', '下饭菜'],
    scenarioTags: ['quick_dinner'],
    flavors: ['咸鲜', '下饭', '开胃'],
    primaryFlavor: '咸鲜',
    equipmentNeeded: ['stove'],
    totalTimeMinutes: 15,
    difficulty: 1,
    servings: 2,
    ingredients: [
      { name: '羊肉片', amount: '300g', category: 'meat', isStaple: false },
      { name: '大葱', amount: '3根', category: 'vegetable', isStaple: false },
      { name: '姜', amount: '3片', category: 'other', isStaple: true },
    ],
    seasonings: [
      { name: '生抽', amount: '2勺', isStaple: true },
      { name: '料酒', amount: '1勺', isStaple: true },
      { name: '孜然粉', amount: '半勺', isStaple: false },
    ],
    steps: [
      { order: 1, description: '大葱斜切段，姜切丝', durationMinutes: 2, fireHint: 'off', assignedTo: 'B' },
      { order: 2, description: '热锅凉油，大火爆香姜丝', durationMinutes: 1, fireHint: 'high', assignedTo: 'A' },
      { order: 3, description: '下羊肉片大火快速滑炒至变色', durationMinutes: 2, fireHint: 'high', warning: '全程大火，羊肉不要炒老', assignedTo: 'A' },
      { order: 4, description: '下葱段、生抽、料酒、孜然粉，大火翻匀出锅', durationMinutes: 2, fireHint: 'high', assignedTo: 'A' },
    ],
  },

  // ═══════════════════════════════════════════════════════
  // 素菜 (9 more)
  // ═══════════════════════════════════════════════════════
  {
    name: '酸辣土豆丝',
    type: '素菜',
    tags: ['家常菜', '快手菜', '下饭菜', '开胃菜'],
    scenarioTags: ['quick_dinner'],
    flavors: ['酸辣', '下饭', '开胃'],
    primaryFlavor: '酸辣',
    equipmentNeeded: ['stove'],
    totalTimeMinutes: 12,
    difficulty: 1,
    servings: 2,
    ingredients: [
      { name: '土豆', amount: '2个', category: 'vegetable', isStaple: false },
      { name: '干辣椒', amount: '4个', category: 'other', isStaple: true },
      { name: '蒜', amount: '3瓣', category: 'other', isStaple: true },
      { name: '花椒', amount: '1小勺', category: 'other', isStaple: true },
    ],
    seasonings: [
      { name: '白醋', amount: '2勺', isStaple: true },
      { name: '盐', amount: '适量', isStaple: true },
    ],
    steps: [
      { order: 1, description: '土豆切细丝，冷水浸泡去淀粉后沥干', durationMinutes: 5, fireHint: 'off', assignedTo: 'B' },
      { order: 2, description: '干辣椒切段，蒜切片', durationMinutes: 1, fireHint: 'off', assignedTo: 'B' },
      { order: 3, description: '热油爆香花椒后捞出，下干辣椒蒜片', durationMinutes: 1, fireHint: 'high', assignedTo: 'A' },
      { order: 4, description: '下土豆丝大火快炒，沿锅边淋醋，加盐', durationMinutes: 3, fireHint: 'high', warning: '全程大火快炒，不超过4分钟', assignedTo: 'A' },
    ],
  },
  {
    name: '番茄炒蛋',
    type: '素菜',
    tags: ['家常菜', '快手菜', '懒人菜'],
    scenarioTags: ['quick_dinner', 'lazy_meal'],
    flavors: ['酸甜', '开胃', '下饭'],
    primaryFlavor: '酸甜',
    equipmentNeeded: ['stove'],
    totalTimeMinutes: 10,
    difficulty: 1,
    servings: 2,
    ingredients: [
      { name: '番茄', amount: '2个', category: 'vegetable', isStaple: false },
      { name: '鸡蛋', amount: '3个', category: 'egg_dairy', isStaple: true },
      { name: '葱', amount: '1根', category: 'other', isStaple: true },
    ],
    seasonings: [
      { name: '盐', amount: '适量', isStaple: true },
      { name: '白糖', amount: '半勺', isStaple: true },
    ],
    steps: [
      { order: 1, description: '番茄切块，鸡蛋打散加少许盐，葱切花', durationMinutes: 3, fireHint: 'off', assignedTo: 'B' },
      { order: 2, description: '热油炒鸡蛋至凝固盛出', durationMinutes: 2, fireHint: 'high', assignedTo: 'A' },
      { order: 3, description: '热油下番茄炒出汁，加糖', durationMinutes: 3, fireHint: 'medium', assignedTo: 'A' },
      { order: 4, description: '鸡蛋回锅翻匀，加盐撒葱花出锅', durationMinutes: 1, fireHint: 'high', assignedTo: 'A' },
    ],
  },
  {
    name: '手撕包菜',
    type: '素菜',
    tags: ['家常菜', '快手菜', '下饭菜', '减脂餐'],
    scenarioTags: ['quick_dinner'],
    flavors: ['辣', '下饭', '开胃'],
    primaryFlavor: '辣',
    equipmentNeeded: ['stove'],
    totalTimeMinutes: 10,
    difficulty: 1,
    servings: 2,
    ingredients: [
      { name: '包菜', amount: '半个', category: 'vegetable', isStaple: false },
      { name: '干辣椒', amount: '5个', category: 'other', isStaple: true },
      { name: '蒜', amount: '3瓣', category: 'other', isStaple: true },
    ],
    seasonings: [
      { name: '生抽', amount: '1勺', isStaple: true },
      { name: '醋', amount: '1勺', isStaple: true },
      { name: '盐', amount: '适量', isStaple: true },
    ],
    steps: [
      { order: 1, description: '包菜手撕成小片洗净沥干，干辣椒切段，蒜切片', durationMinutes: 3, fireHint: 'off', assignedTo: 'B' },
      { order: 2, description: '热油爆香干辣椒蒜片', durationMinutes: 1, fireHint: 'high', assignedTo: 'A' },
      { order: 3, description: '下包菜大火爆炒，沿锅边淋生抽和醋', durationMinutes: 4, fireHint: 'high', warning: '全程大火，包菜断生即可，不要炒软', assignedTo: 'A' },
      { order: 4, description: '加盐翻匀出锅', durationMinutes: 1, fireHint: 'high', assignedTo: 'A' },
    ],
  },
  {
    name: '蒜蓉西兰花',
    type: '素菜',
    tags: ['家常菜', '快手菜', '减脂餐'],
    scenarioTags: ['quick_dinner'],
    flavors: ['清淡', '清爽', '解腻'],
    primaryFlavor: '清淡',
    equipmentNeeded: ['stove'],
    totalTimeMinutes: 10,
    difficulty: 1,
    servings: 2,
    ingredients: [
      { name: '西兰花', amount: '1棵', category: 'vegetable', isStaple: false },
      { name: '蒜', amount: '5瓣', category: 'other', isStaple: true },
    ],
    seasonings: [
      { name: '蚝油', amount: '1勺', isStaple: false },
      { name: '盐', amount: '适量', isStaple: true },
    ],
    steps: [
      { order: 1, description: '西兰花掰小朵，淡盐水浸泡10分钟后洗净', durationMinutes: 10, fireHint: 'off', assignedTo: 'B' },
      { order: 2, description: '蒜切末', durationMinutes: 1, fireHint: 'off', assignedTo: 'B' },
      { order: 3, description: '水开加少许盐和油，焯西兰花1分钟捞出', durationMinutes: 2, fireHint: 'high', assignedTo: 'A' },
      { order: 4, description: '热油小火炒香蒜末，下西兰花、蚝油、盐翻炒均匀', durationMinutes: 2, fireHint: 'medium', assignedTo: 'A' },
    ],
  },
  {
    name: '地三鲜',
    type: '素菜',
    tags: ['家常菜', '下饭菜', '双人餐'],
    scenarioTags: ['weekend_date'],
    flavors: ['咸鲜', '下饭', '热乎'],
    primaryFlavor: '咸鲜',
    equipmentNeeded: ['stove'],
    totalTimeMinutes: 25,
    difficulty: 2,
    servings: 2,
    ingredients: [
      { name: '土豆', amount: '1个', category: 'vegetable', isStaple: false },
      { name: '茄子', amount: '1根', category: 'vegetable', isStaple: false },
      { name: '青椒', amount: '1个', category: 'vegetable', isStaple: false },
      { name: '蒜', amount: '4瓣', category: 'other', isStaple: true },
    ],
    seasonings: [
      { name: '生抽', amount: '2勺', isStaple: true },
      { name: '老抽', amount: '半勺', isStaple: true },
      { name: '白糖', amount: '半勺', isStaple: true },
      { name: '淀粉', amount: '1勺', isStaple: true },
    ],
    steps: [
      { order: 1, description: '土豆、茄子、青椒切滚刀块。茄子撒盐腌10分钟挤干水分（去涩少吸油）', durationMinutes: 12, fireHint: 'off', assignedTo: 'B' },
      { order: 2, description: '蒜切末。调碗汁：生抽+老抽+糖+淀粉+3勺水', durationMinutes: 2, fireHint: 'off', assignedTo: 'B' },
      { order: 3, description: '多油，土豆炸至金黄捞出，茄子炸软捞出', durationMinutes: 6, fireHint: 'medium', assignedTo: 'A' },
      { order: 4, description: '锅留底油爆香蒜末，下青椒翻炒', durationMinutes: 2, fireHint: 'high', assignedTo: 'A' },
      { order: 5, description: '土豆茄子回锅，倒入碗汁大火翻匀收汁出锅', durationMinutes: 2, fireHint: 'high', assignedTo: 'A' },
    ],
  },
  {
    name: '蚝油生菜',
    type: '素菜',
    tags: ['快手菜', '减脂餐'],
    scenarioTags: ['quick_dinner'],
    flavors: ['清淡', '解腻', '清爽'],
    primaryFlavor: '清淡',
    equipmentNeeded: ['stove'],
    totalTimeMinutes: 7,
    difficulty: 1,
    servings: 2,
    ingredients: [
      { name: '生菜', amount: '2棵', category: 'vegetable', isStaple: false },
      { name: '蒜', amount: '4瓣', category: 'other', isStaple: true },
    ],
    seasonings: [
      { name: '蚝油', amount: '2勺', isStaple: false },
      { name: '生抽', amount: '1勺', isStaple: true },
    ],
    steps: [
      { order: 1, description: '生菜洗净，蒜切末', durationMinutes: 2, fireHint: 'off', assignedTo: 'B' },
      { order: 2, description: '水开下生菜焯20秒捞出装盘', durationMinutes: 1, fireHint: 'high', warning: '焯水时间不要超过30秒', assignedTo: 'A' },
      { order: 3, description: '热油爆香蒜末，加蚝油生抽和2勺水煮开，浇在生菜上', durationMinutes: 2, fireHint: 'medium', assignedTo: 'A' },
    ],
  },
  {
    name: '红烧茄子',
    type: '素菜',
    tags: ['家常菜', '下饭菜', '双人餐'],
    scenarioTags: ['quick_dinner'],
    flavors: ['咸鲜', '下饭', '热乎'],
    primaryFlavor: '咸鲜',
    equipmentNeeded: ['stove'],
    totalTimeMinutes: 20,
    difficulty: 2,
    servings: 2,
    ingredients: [
      { name: '茄子', amount: '2根', category: 'vegetable', isStaple: false },
      { name: '蒜', amount: '4瓣', category: 'other', isStaple: true },
      { name: '葱', amount: '1根', category: 'other', isStaple: true },
    ],
    seasonings: [
      { name: '生抽', amount: '2勺', isStaple: true },
      { name: '老抽', amount: '半勺', isStaple: true },
      { name: '白糖', amount: '1勺', isStaple: true },
      { name: '淀粉', amount: '1勺', isStaple: true },
    ],
    steps: [
      { order: 1, description: '茄子切滚刀块，撒盐腌10分钟挤干水分', durationMinutes: 12, fireHint: 'off', assignedTo: 'B' },
      { order: 2, description: '蒜切末，葱切花。调碗汁：生抽+老抽+糖+淀粉+半碗水', durationMinutes: 2, fireHint: 'off', assignedTo: 'B' },
      { order: 3, description: '热油下茄子翻炒至变软微黄', durationMinutes: 4, fireHint: 'high', assignedTo: 'A' },
      { order: 4, description: '倒入碗汁，中火烧2分钟收汁，撒葱花出锅', durationMinutes: 3, fireHint: 'medium', assignedTo: 'A' },
    ],
  },
  {
    name: '干煸四季豆',
    type: '素菜',
    tags: ['家常菜', '下饭菜', '开胃菜'],
    scenarioTags: ['weekend_date'],
    flavors: ['辣', '下饭', '开胃'],
    primaryFlavor: '辣',
    equipmentNeeded: ['stove'],
    totalTimeMinutes: 20,
    difficulty: 2,
    servings: 2,
    ingredients: [
      { name: '四季豆', amount: '300g', category: 'vegetable', isStaple: false },
      { name: '干辣椒', amount: '6个', category: 'other', isStaple: true },
      { name: '花椒', amount: '1小勺', category: 'other', isStaple: true },
      { name: '蒜', amount: '4瓣', category: 'other', isStaple: true },
    ],
    seasonings: [
      { name: '生抽', amount: '1勺', isStaple: true },
      { name: '盐', amount: '适量', isStaple: true },
    ],
    steps: [
      { order: 1, description: '四季豆去筋掰段，洗净彻底沥干（有水入锅会溅油）', durationMinutes: 5, fireHint: 'off', assignedTo: 'B' },
      { order: 2, description: '干辣椒切段，蒜切末', durationMinutes: 2, fireHint: 'off', assignedTo: 'B' },
      { order: 3, description: '锅中多油，下四季豆中火煸至表面起皱微焦捞出', durationMinutes: 8, fireHint: 'medium', warning: '一定要煸熟，生四季豆有毒', assignedTo: 'A' },
      { order: 4, description: '锅留底油，爆香花椒干辣椒蒜末，四季豆回锅加生抽盐翻匀', durationMinutes: 2, fireHint: 'high', assignedTo: 'A' },
    ],
  },
  {
    name: '香菇青菜',
    type: '素菜',
    tags: ['家常菜', '快手菜', '减脂餐'],
    scenarioTags: ['quick_dinner'],
    flavors: ['清淡', '清爽', '解腻'],
    primaryFlavor: '清淡',
    equipmentNeeded: ['stove'],
    totalTimeMinutes: 12,
    difficulty: 1,
    servings: 2,
    ingredients: [
      { name: '上海青（小油菜）', amount: '300g', category: 'vegetable', isStaple: false },
      { name: '鲜香菇', amount: '6朵', category: 'vegetable', isStaple: false },
      { name: '蒜', amount: '3瓣', category: 'other', isStaple: true },
    ],
    seasonings: [
      { name: '蚝油', amount: '1勺', isStaple: false },
      { name: '盐', amount: '适量', isStaple: true },
    ],
    steps: [
      { order: 1, description: '香菇切片，青菜洗净对半切，蒜切片', durationMinutes: 4, fireHint: 'off', assignedTo: 'B' },
      { order: 2, description: '热油爆香蒜片，下香菇炒软出香', durationMinutes: 3, fireHint: 'medium', assignedTo: 'A' },
      { order: 3, description: '下青菜大火翻炒至断生，加蚝油盐翻匀出锅', durationMinutes: 3, fireHint: 'high', assignedTo: 'A' },
    ],
  },

  // ═══════════════════════════════════════════════════════
  // 汤 (6 more)
  // ═══════════════════════════════════════════════════════
  {
    name: '冬瓜排骨汤',
    type: '汤',
    tags: ['家常菜', '双人餐', '减脂餐'],
    scenarioTags: ['weekend_date'],
    flavors: ['清淡', '热乎', '想喝汤', '解腻'],
    primaryFlavor: '清淡',
    equipmentNeeded: ['stove'],
    totalTimeMinutes: 55,
    difficulty: 1,
    servings: 2,
    ingredients: [
      { name: '排骨', amount: '300g', category: 'meat', isStaple: false },
      { name: '冬瓜', amount: '300g', category: 'vegetable', isStaple: false },
      { name: '姜', amount: '5片', category: 'other', isStaple: true },
      { name: '葱', amount: '1根', category: 'other', isStaple: true },
    ],
    seasonings: [
      { name: '料酒', amount: '1勺', isStaple: true },
      { name: '盐', amount: '适量', isStaple: true },
    ],
    steps: [
      { order: 1, description: '排骨冷水下锅加姜片料酒焯水捞出', durationMinutes: 8, fireHint: 'high', assignedTo: 'B' },
      { order: 2, description: '冬瓜去皮切块', durationMinutes: 3, fireHint: 'off', assignedTo: 'B' },
      { order: 3, description: '排骨入砂锅/汤锅，加足量水、姜片，大火煮开转小火炖30分钟', durationMinutes: 32, fireHint: 'low', assignedTo: 'A' },
      { order: 4, description: '下冬瓜继续炖10分钟至透明', durationMinutes: 10, fireHint: 'low', assignedTo: 'A' },
      { order: 5, description: '加盐调味，撒葱花出锅', durationMinutes: 1, fireHint: 'off', assignedTo: 'A' },
    ],
  },
  {
    name: '酸辣汤',
    type: '汤',
    tags: ['家常菜', '快手菜', '开胃菜'],
    scenarioTags: ['quick_dinner'],
    flavors: ['酸辣', '开胃', '热乎', '想喝汤'],
    primaryFlavor: '酸辣',
    equipmentNeeded: ['stove'],
    totalTimeMinutes: 15,
    difficulty: 1,
    servings: 2,
    ingredients: [
      { name: '鸡蛋', amount: '1个', category: 'egg_dairy', isStaple: true },
      { name: '豆腐', amount: '半盒', category: 'other', isStaple: false },
      { name: '木耳', amount: '5朵（泡发）', category: 'vegetable', isStaple: false },
      { name: '火腿肠', amount: '半根', category: 'meat', isStaple: false },
    ],
    seasonings: [
      { name: '醋', amount: '3勺', isStaple: true },
      { name: '白胡椒粉', amount: '1勺', isStaple: true },
      { name: '生抽', amount: '1勺', isStaple: true },
      { name: '淀粉', amount: '2勺', isStaple: true },
      { name: '香油', amount: '少许', isStaple: false },
    ],
    steps: [
      { order: 1, description: '豆腐、木耳、火腿肠切丝，鸡蛋打散', durationMinutes: 5, fireHint: 'off', assignedTo: 'B' },
      { order: 2, description: '锅中加水烧开，下豆腐丝木耳丝火腿丝，加生抽', durationMinutes: 3, fireHint: 'high', assignedTo: 'A' },
      { order: 3, description: '水淀粉勾芡，转圈淋入蛋液成蛋花', durationMinutes: 2, fireHint: 'medium', assignedTo: 'A' },
      { order: 4, description: '关火，加醋、白胡椒粉、香油搅匀出锅', durationMinutes: 1, fireHint: 'off', assignedTo: 'A' },
    ],
  },
  {
    name: '玉米排骨汤',
    type: '汤',
    tags: ['家常菜', '双人餐'],
    scenarioTags: ['weekend_date'],
    flavors: ['清淡', '想喝汤', '热乎', '甜口'],
    primaryFlavor: '清淡',
    equipmentNeeded: ['stove'],
    totalTimeMinutes: 60,
    difficulty: 1,
    servings: 2,
    ingredients: [
      { name: '排骨', amount: '300g', category: 'meat', isStaple: false },
      { name: '甜玉米', amount: '1根', category: 'vegetable', isStaple: false },
      { name: '胡萝卜', amount: '1根', category: 'vegetable', isStaple: false },
      { name: '姜', amount: '3片', category: 'other', isStaple: true },
    ],
    seasonings: [
      { name: '料酒', amount: '1勺', isStaple: true },
      { name: '盐', amount: '适量', isStaple: true },
    ],
    steps: [
      { order: 1, description: '排骨焯水捞出，玉米切段，胡萝卜切滚刀块', durationMinutes: 8, fireHint: 'high', assignedTo: 'B' },
      { order: 2, description: '排骨、玉米、姜片入锅加足量水，大火煮开转小火炖40分钟', durationMinutes: 42, fireHint: 'low', assignedTo: 'A' },
      { order: 3, description: '加入胡萝卜继续炖10分钟', durationMinutes: 10, fireHint: 'low', assignedTo: 'A' },
      { order: 4, description: '加盐调味出锅', durationMinutes: 1, fireHint: 'off', assignedTo: 'together' },
    ],
  },
  {
    name: '菌菇豆腐汤',
    type: '汤',
    tags: ['家常菜', '快手菜', '减脂餐', '懒人菜'],
    scenarioTags: ['quick_dinner', 'lazy_meal'],
    flavors: ['清淡', '想喝汤', '清爽'],
    primaryFlavor: '清淡',
    equipmentNeeded: ['stove'],
    totalTimeMinutes: 15,
    difficulty: 1,
    servings: 2,
    ingredients: [
      { name: '嫩豆腐', amount: '1盒', category: 'other', isStaple: false },
      { name: '金针菇', amount: '1把', category: 'vegetable', isStaple: false },
      { name: '鲜香菇', amount: '4朵', category: 'vegetable', isStaple: false },
      { name: '葱', amount: '1根', category: 'other', isStaple: true },
    ],
    seasonings: [
      { name: '盐', amount: '适量', isStaple: true },
      { name: '白胡椒粉', amount: '少许', isStaple: true },
      { name: '香油', amount: '少许', isStaple: false },
    ],
    steps: [
      { order: 1, description: '豆腐切小块，香菇切片，金针菇去根撕开，葱切花', durationMinutes: 4, fireHint: 'off', assignedTo: 'B' },
      { order: 2, description: '水烧开，下香菇金针菇煮3分钟', durationMinutes: 4, fireHint: 'high', assignedTo: 'A' },
      { order: 3, description: '轻轻滑入豆腐，煮2分钟', durationMinutes: 2, fireHint: 'medium', assignedTo: 'A' },
      { order: 4, description: '加盐、白胡椒粉、香油、葱花出锅', durationMinutes: 1, fireHint: 'off', assignedTo: 'A' },
    ],
  },
  {
    name: '西红柿牛腩汤',
    type: '汤',
    tags: ['家常菜', '硬菜', '双人餐'],
    scenarioTags: ['weekend_date'],
    flavors: ['酸辣', '开胃', '热乎', '想喝汤'],
    primaryFlavor: '酸辣',
    equipmentNeeded: ['stove'],
    totalTimeMinutes: 80,
    difficulty: 2,
    servings: 2,
    ingredients: [
      { name: '牛腩', amount: '400g', category: 'meat', isStaple: false },
      { name: '番茄', amount: '3个', category: 'vegetable', isStaple: false },
      { name: '洋葱', amount: '半个', category: 'vegetable', isStaple: false },
      { name: '姜', amount: '5片', category: 'other', isStaple: true },
    ],
    seasonings: [
      { name: '番茄酱', amount: '2勺', isStaple: false },
      { name: '料酒', amount: '2勺', isStaple: true },
      { name: '盐', amount: '适量', isStaple: true },
    ],
    steps: [
      { order: 1, description: '牛腩切块，冷水下锅加姜片料酒焯水捞出', durationMinutes: 10, fireHint: 'high', assignedTo: 'B' },
      { order: 2, description: '番茄切块，洋葱切丁', durationMinutes: 3, fireHint: 'off', assignedTo: 'B' },
      { order: 3, description: '热油炒洋葱至透明，下番茄炒出汁，加番茄酱', durationMinutes: 5, fireHint: 'medium', assignedTo: 'A' },
      { order: 4, description: '下牛腩翻炒，加足量热水，大火煮开转小火炖60分钟', durationMinutes: 62, fireHint: 'low', assignedTo: 'A' },
      { order: 5, description: '加盐调味出锅', durationMinutes: 1, fireHint: 'off', assignedTo: 'A' },
    ],
  },
  {
    name: '白菜豆腐汤',
    type: '汤',
    tags: ['家常菜', '快手菜', '懒人菜', '减脂餐'],
    scenarioTags: ['quick_dinner', 'lazy_meal'],
    flavors: ['清淡', '想喝汤', '清爽', '解腻'],
    primaryFlavor: '清淡',
    equipmentNeeded: ['stove'],
    totalTimeMinutes: 10,
    difficulty: 1,
    servings: 2,
    ingredients: [
      { name: '大白菜', amount: '4片', category: 'vegetable', isStaple: false },
      { name: '嫩豆腐', amount: '半盒', category: 'other', isStaple: false },
      { name: '葱', amount: '1根', category: 'other', isStaple: true },
      { name: '姜', amount: '2片', category: 'other', isStaple: true },
    ],
    seasonings: [
      { name: '盐', amount: '适量', isStaple: true },
      { name: '白胡椒粉', amount: '少许', isStaple: true },
      { name: '香油', amount: '少许', isStaple: false },
    ],
    steps: [
      { order: 1, description: '白菜切段，豆腐切小块，姜切丝，葱切花', durationMinutes: 3, fireHint: 'off', assignedTo: 'B' },
      { order: 2, description: '水烧开，下姜丝白菜煮3分钟至软', durationMinutes: 4, fireHint: 'high', assignedTo: 'A' },
      { order: 3, description: '下豆腐煮2分钟，加盐、白胡椒粉、香油、葱花出锅', durationMinutes: 2, fireHint: 'medium', assignedTo: 'A' },
    ],
  },

  // ═══════════════════════════════════════════════════════
  // 主食 (5 more)
  // ═══════════════════════════════════════════════════════
  {
    name: '白米饭',
    type: '主食',
    tags: ['家常菜', '懒人菜'],
    scenarioTags: ['quick_dinner', 'lazy_meal'],
    flavors: ['清淡'],
    primaryFlavor: '清淡',
    equipmentNeeded: ['rice_cooker'],
    totalTimeMinutes: 30,
    difficulty: 1,
    servings: 2,
    ingredients: [
      { name: '大米', amount: '1.5杯', category: 'staple', isStaple: true },
    ],
    seasonings: [],
    steps: [
      { order: 1, description: '大米淘洗2遍，加水至对应刻度', durationMinutes: 2, fireHint: 'off', assignedTo: 'B' },
      { order: 2, description: '按下煮饭键，跳闸后焖5分钟', durationMinutes: 28, fireHint: 'off', assignedTo: 'A' },
    ],
  },
  {
    name: '番茄鸡蛋面',
    type: '主食',
    tags: ['家常菜', '快手菜', '懒人菜'],
    scenarioTags: ['quick_dinner', 'lazy_meal'],
    flavors: ['酸甜', '开胃', '热乎'],
    primaryFlavor: '酸甜',
    equipmentNeeded: ['stove'],
    totalTimeMinutes: 15,
    difficulty: 1,
    servings: 2,
    ingredients: [
      { name: '面条', amount: '200g', category: 'staple', isStaple: false },
      { name: '番茄', amount: '2个', category: 'vegetable', isStaple: false },
      { name: '鸡蛋', amount: '2个', category: 'egg_dairy', isStaple: true },
      { name: '葱', amount: '1根', category: 'other', isStaple: true },
    ],
    seasonings: [
      { name: '生抽', amount: '1勺', isStaple: true },
      { name: '盐', amount: '适量', isStaple: true },
    ],
    steps: [
      { order: 1, description: '番茄切块，鸡蛋打散，葱切花', durationMinutes: 3, fireHint: 'off', assignedTo: 'B' },
      { order: 2, description: '另起锅煮面条至8分熟捞出过凉水', durationMinutes: 5, fireHint: 'high', assignedTo: 'B' },
      { order: 3, description: '热油炒鸡蛋盛出，同锅炒番茄出汁，加生抽和一碗水煮开', durationMinutes: 4, fireHint: 'medium', assignedTo: 'A' },
      { order: 4, description: '下面条和鸡蛋煮1分钟，加盐撒葱花出锅', durationMinutes: 2, fireHint: 'high', assignedTo: 'A' },
    ],
  },
  {
    name: '葱油拌面',
    type: '主食',
    tags: ['家常菜', '快手菜', '懒人菜'],
    scenarioTags: ['quick_dinner', 'lazy_meal'],
    flavors: ['咸鲜', '开胃'],
    primaryFlavor: '咸鲜',
    equipmentNeeded: ['stove'],
    totalTimeMinutes: 15,
    difficulty: 1,
    servings: 2,
    ingredients: [
      { name: '面条', amount: '200g', category: 'staple', isStaple: false },
      { name: '小葱', amount: '5根', category: 'other', isStaple: false },
    ],
    seasonings: [
      { name: '生抽', amount: '3勺', isStaple: true },
      { name: '老抽', amount: '1勺', isStaple: true },
      { name: '白糖', amount: '半勺', isStaple: true },
    ],
    steps: [
      { order: 1, description: '葱切段，葱白葱绿分开。调酱汁：生抽+老抽+糖', durationMinutes: 2, fireHint: 'off', assignedTo: 'B' },
      { order: 2, description: '煮面条至熟捞出过凉水沥干装碗', durationMinutes: 6, fireHint: 'high', assignedTo: 'B' },
      { order: 3, description: '热油小火炸葱白至微黄，下葱绿炸至焦黄捞出', durationMinutes: 5, fireHint: 'low', warning: '小火慢炸，大火葱会糊', assignedTo: 'A' },
      { order: 4, description: '关火，酱汁倒入葱油中搅匀，浇在面条上拌匀', durationMinutes: 1, fireHint: 'off', assignedTo: 'A' },
    ],
  },
  {
    name: '什锦炒饭',
    type: '主食',
    tags: ['家常菜', '快手菜', '剩菜改造', '懒人菜'],
    scenarioTags: ['quick_dinner', 'lazy_meal'],
    flavors: ['咸鲜', '下饭'],
    primaryFlavor: '咸鲜',
    equipmentNeeded: ['stove', 'rice_cooker'],
    totalTimeMinutes: 12,
    difficulty: 1,
    servings: 2,
    ingredients: [
      { name: '米饭', amount: '2碗（隔夜）', category: 'staple', isStaple: true },
      { name: '鸡蛋', amount: '2个', category: 'egg_dairy', isStaple: true },
      { name: '火腿肠', amount: '1根', category: 'meat', isStaple: false },
      { name: '冷冻蔬菜粒', amount: '半碗（青豆玉米胡萝卜）', category: 'vegetable', isStaple: false },
      { name: '葱', amount: '2根', category: 'other', isStaple: true },
    ],
    seasonings: [
      { name: '盐', amount: '适量', isStaple: true },
    ],
    steps: [
      { order: 1, description: '火腿肠切丁，鸡蛋打散，葱切花', durationMinutes: 3, fireHint: 'off', assignedTo: 'B' },
      { order: 2, description: '热油炒鸡蛋盛出，同锅炒火腿丁和蔬菜粒', durationMinutes: 3, fireHint: 'high', assignedTo: 'A' },
      { order: 3, description: '下米饭炒散，鸡蛋回锅，加盐翻炒均匀', durationMinutes: 4, fireHint: 'high', assignedTo: 'A' },
      { order: 4, description: '撒葱花翻匀出锅', durationMinutes: 1, fireHint: 'off', assignedTo: 'A' },
    ],
  },
  {
    name: '红烧牛肉面',
    type: '主食',
    tags: ['家常菜', '硬菜', '双人餐'],
    scenarioTags: ['weekend_date'],
    flavors: ['辣', '下饭', '热乎'],
    primaryFlavor: '辣',
    equipmentNeeded: ['stove'],
    totalTimeMinutes: 75,
    difficulty: 2,
    servings: 2,
    ingredients: [
      { name: '牛腩', amount: '300g', category: 'meat', isStaple: false },
      { name: '面条', amount: '200g', category: 'staple', isStaple: false },
      { name: '番茄', amount: '1个', category: 'vegetable', isStaple: false },
      { name: '姜', amount: '5片', category: 'other', isStaple: true },
      { name: '葱', amount: '2根', category: 'other', isStaple: true },
      { name: '八角', amount: '2个', category: 'other', isStaple: false },
      { name: '青菜', amount: '2棵', category: 'vegetable', isStaple: false },
    ],
    seasonings: [
      { name: '豆瓣酱', amount: '1勺', isStaple: false },
      { name: '生抽', amount: '2勺', isStaple: true },
      { name: '老抽', amount: '1勺', isStaple: true },
      { name: '料酒', amount: '2勺', isStaple: true },
    ],
    steps: [
      { order: 1, description: '牛腩切块冷水焯水捞出，番茄切块', durationMinutes: 8, fireHint: 'high', assignedTo: 'B' },
      { order: 2, description: '热油炒香豆瓣酱，下牛腩翻炒，加姜葱八角生抽老抽料酒', durationMinutes: 5, fireHint: 'high', assignedTo: 'A' },
      { order: 3, description: '下番茄，加足量热水，大火煮开转小火炖60分钟', durationMinutes: 62, fireHint: 'low', assignedTo: 'A' },
      { order: 4, description: '另起锅煮面条和青菜至熟，捞入碗中，浇上牛肉汤和牛肉', durationMinutes: 6, fireHint: 'high', assignedTo: 'B' },
    ],
  },
];
